### ISSUE TITLE
How to evaluate vertical lines?

### ISSUE THREAD

**Issue by beratkurar** [DIVA-DIA/LineSegmentationEvaluator#1]
Hi,

I've used this evaluator to evaluate a document with vertical lines.
My prediction visually seems ok. But evaluator gives a poor performance.
Looking at the following samples what do you think can be the problem?

Thank you. 
Evaluator output:
<img width="303" alt="evaluator_output" src="https://user-images.githubusercontent.com/10862248/56667778-20fcd680-66b7-11e9-8595-d2eb9e824a66.png">

Ground truth:
<img width="303" alt="ground_truth" src="https://user-images.githubusercontent.com/10862248/56667779-20fcd680-66b7-11e9-98d8-ad0071a61cac.png">

Prediction:
<img width="303" alt="prediction" src="https://user-images.githubusercontent.com/10862248/56667780-21956d00-66b7-11e9-9b4f-fd771b7e031f.png">

**Comment by beratkurar** [comment]
Here is the log from evaluator:
[evaluator_log_vertical_lines.txt](https://github.com/DIVA-DIA/DIVA_Line_Segmentation_Evaluator/files/3112814/evaluator_log_vertical_lines.txt)

**Comment by Renthal** [comment]
Hi Berat,

I see from the log that the tool detects 20 polygons in the XML ground truth and 19 polygons in the prediction output.
However, form the attached images it seems to be it should be 7 lines for the GT.
Could you investigate this first?
AFAIK the tool should have no issues with vertical lines 😊

___________________________________________
Michele Alberti
Ph.D Candidate at University of Fribourg
Document Image Voice Analysis Group
Tel. +41 76 224 75 58<tel:+41%2076%20224%2075%2058>
albertimichele91@hotmail.com<mailto:albertimichele91@hotmail.com>
michele.alberti@unifr.ch<mailto:michele.alberti@unifr.ch>

**Comment by beratkurar** [comment]
Yes you are right. In the above I've attached only a part of a whole document.
Whole document images are in the below:

Whole evalution:
![whole_evaluation](https://user-images.githubusercontent.com/10862248/56670979-77204880-66bc-11e9-8123-84703ff4dc67.png)

Whole prediction:
![whole_prediction](https://user-images.githubusercontent.com/10862248/56670981-77204880-66bc-11e9-906f-37c5a2e3b365.png)

Whole truth:
![whole_truth](https://user-images.githubusercontent.com/10862248/56670982-77b8df00-66bc-11e9-96ad-c24e5f7f1308.png)

**Comment by Renthal** [comment]
I see. Could you send the xml files as well as the input (original image) such that I can try to reproduce the problem ?


___________________________________________
Michele Alberti
Ph.D Candidate at University of Fribourg
Document Image Voice Analysis Group
Tel. +41 76 224 75 58<tel:+41%2076%20224%2075%2058>
albertimichele91@hotmail.com<mailto:albertimichele91@hotmail.com>
michele.alberti@unifr.ch<mailto:michele.alberti@unifr.ch>

**Comment by beratkurar** [comment]
Please find them in the attachment.
![image](https://user-images.githubusercontent.com/10862248/56671724-cadf6180-66bd-11e9-9e7c-29e84512d569.png)

**Comment by beratkurar** [comment]
[prediction_page_format.txt](https://github.com/DIVA-DIA/DIVA_Line_Segmentation_Evaluator/files/3112999/prediction_page_format.txt)

[truth_page_format.txt](https://github.com/DIVA-DIA/DIVA_Line_Segmentation_Evaluator/files/3113010/truth_page_format.txt)

![image](https://user-images.githubusercontent.com/10862248/56672134-8a341800-66be-11e9-8145-7bd5c40acb95.png)

**Comment by Renthal** [comment]
Is the attached image your pixel level gt (white black image)? If yes; the format is not what the tool expects as the classes should be encoded in the blue channel (see website of the competition or below).

To be more precise, the ground truth at pixels level has to be defined as reported here: https://github.com/DIVA-DIA/DIVA_Layout_Analysis_Evaluator 
This is important as the foreground pixels are used to determine the actual location of the text on the image; this is in turn used to compute the score to match the polygons. 

___________________________________________
Michele Alberti
Ph.D Candidate at University of Fribourg
Document Image Voice Analysis Group
Tel. +41 76 224 75 58<tel:+41%2076%20224%2075%2058>
albertimichele91@hotmail.com<mailto:albertimichele91@hotmail.com>
michele.alberti@unifr.ch<mailto:michele.alberti@unifr.ch>
.
...:

On 24 Apr 2019, at 17:27, Berat Kurar <notifications@github.com<mailto:notifications@github.com>> wrote:


prediction_page_format.txt<https://github.com/DIVA-DIA/DIVA_Line_Segmentation_Evaluator/files/3112999/prediction_page_format.txt>
truth_page.txt<https://github.com/DIVA-DIA/DIVA_Line_Segmentation_Evaluator/files/3113000/truth_page.txt>
[image]<https://user-images.githubusercontent.com/10862248/56672134-8a341800-66be-11e9-8145-7bd5c40acb95.png>

**Comment by beratkurar** [comment]
Attached black&white image is not the pixel level gt.

To prepare the pixel level gt, are the following steps true?

1. set background pixels of binary image to (0,0,1) in rgb
2. set foreground pixels of binary image to (0,0,8) in rgb
3. set boundary pixels  to (128,0,0) in rgb

**Comment by Renthal** [comment]
Almost, change step 2 in:

  *   I will set foreground pixels of binary image to (0,0,2) in rgb
As all the classes are expected to be on a different bit 1,2,4,8,16,32, … on the blue channel.
Let me know if it works
___________________________________________
Michele Alberti
Ph.D Candidate at University of Fribourg
Document Image Voice Analysis Group
Tel. +41 76 224 75 58<tel:+41%2076%20224%2075%2058>
albertimichele91@hotmail.com<mailto:albertimichele91@hotmail.com>
michele.alberti@unifr.ch<mailto:michele.alberti@unifr.ch>

**Comment by beratkurar** [comment]
Here is the result with foreground pixels of binary image = (0,0,8) in rgb

![ms_5-visualization](https://user-images.githubusercontent.com/10862248/56743458-46edae00-677f-11e9-919a-14a37abf0180.png)

**Comment by Renthal** [comment]
I am glad it worked! Thanks :)
