### ISSUE TITLE
What means UI?

### ISSUE THREAD

**Issue by beratkurar** [DIVA-DIA/LineSegmentationEvaluator#2]
Hi,

In the LineSegmentationEvaluator.java at line 330, commented that `in this case the UI`.
Could you please tell what is UI?
I guess it is IU, right?

**Comment by Renthal** [comment]
Hi,

It is a minor spelling mistake and you are right: it is meant to be IU (or IoU) and is short for Intersection Over Union (or Jaccard index). Thank you for pointing it out I fixed it already.
