### ISSUE TITLE
Is "pixel IU" metric same as "RA" in ICDAR2013 handwriting segmentation contest?

### ISSUE THREAD

**Issue by beratkurar** [DIVA-DIA/LineSegmentationEvaluator#3]

**Comment by Renthal** [comment]
The pixel IU metric is well described in [our original paper](https://arxiv.org/abs/1712.01656).
It counts how many pixels have been correctly detected.

**Comment by beratkurar** [comment]
Yes you are right, your metrics are well defined in your paper.
My question was wrong because I was sleepy last night. Intended question is: 
Can we say "Pixel precision" and "Pixel recall" metrics correspond to "Recognition Accuracy" and "Detection rate" metrics of ICDAR2013 handwriting segmentation contest?
As far as I understand yes they correspond, but I would like to make sure by your opinion please.

**Comment by Renthal** [comment]
I am not familiar at the moment with the metrics used in the ICDAR2013 contest. As a hunch, however, "accuracy" should not be compared to precision, whereas detection rate could very well correspond to a recall metric.

**Comment by joapaspe** [comment]
I think these metrics are different. DR and RA only have into account the number of lines matching while pixel metrics consider the number of pixels overlapping between lines.

From what I remember, in ICDAR 2013 the RA and DR are computed after aligning GT and predicted lines. They consider a predicted line to match a GT line if they overlap more than 95%. This is considered as a "hit", counted as o2o. RA and DR are computed by dividing this matching lines by the number of lines in GT and predicted, but do not consider the number of pixel overlapping a part from the threshold.
Pixel recall and precision do have into account the number of pixels matching.

I hope it answers your question.
