### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by tboenig** [DIVA-DIA/LineSegmentationEvaluator#5]
java -jar LineSegmentationEvaluator.jar -igt -image_gt.png -xgt page_gt.xml -xp page_to_evaluate.xml

better? and corrected?

java -jar LineSegmentationEvaluator.jar -igt image_gt.png -xgt page_gt.xml -xp page_to_evaluate.xml

**Comment by Renthal** [comment]
Thank you for pointing that out, I fixed it in the README
